export const site = {
  name: 'FreeIQCheck',
  domain: 'www.freeiqcheck.com',
  url: 'https://www.freeiqcheck.com',
  tagline: 'Free IQ test online with instant results — no email required',
  email: 'hello@freeiqcheck.com',
  primaryKeyword: 'free iq test',
  gaMeasurementId: 'G-T70SB0KFG6',
  adsenseClientId: 'ca-pub-5802094504680008',
  ogImage: '/og-image.svg',
  keywords: [
    'iq test',
    'free iq test',
    'online iq test',
    'average iq',
    'free iq test online',
    'free iq test no email',
    'free iq test with instant results',
    'instant iq score',
    'iq percentile calculator',
    'can iq improve',
    'what is a good iq score',
    'free iq test with results',
    'free iq test with instant results',
    'free iq test and results',
    'best free iq test',
    'free iq tests',
    'free iq test with free results',
    'free iq test with instant results no email',
    'online iq test',
    'free iq check',
    'logical reasoning test',
    'brain test online',
  ],
} as const;

export const navLinks = [
  { href: '/', label: 'Home' },
  { href: '/test', label: 'Take Quiz' },
  { href: '/brain-lab', label: 'Brain Lab' },
  { href: '/blog', label: 'Blog' },
  { href: '/about', label: 'About' },
  { href: '/faq', label: 'FAQ' },
  { href: '/contact', label: 'Contact' },
] as const;

export const seoNavLinks = [
  { href: '/test', label: 'Free IQ test' },
  { href: '/methodology', label: 'Methodology' },
  { href: '/what-is-iq', label: 'What is IQ?' },
  { href: '/practice-iq-questions', label: 'Practice questions' },
  { href: '/are-online-iq-tests-accurate', label: 'Test accuracy' },
  { href: '/iq-score-chart', label: 'IQ score chart' },
  { href: '/faq', label: 'FAQ' },
] as const;
